# -*- coding: utf-8 -*-
"""execute.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11fmW_MxaqeBhjrShwx3cpxB51LuPe_zu
"""

preprocess_sr.py --min 68 --max 72
preprocess_sr.py --min 73 --max 76
preprocess_sr.py --min 77 --max 80
preprocess_sr.py --min 81 --max 84
preprocess_sr.py --min 85 --max 88
preprocess_sr.py --min 89 --max 92

train.py -c configs/freevc-s.json -m freevc-s