# -*- coding: utf-8 -*-
"""test.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WQpEgiTu-9Rwm_A2jR7bsQ5yLECNU5cm
"""

train.py -c "configs/freevc-s.json" -m freevc-s
