# Generated by Django 4.2.1 on 2023-05-20 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiofileserializer',
            name='audio_file',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
