# Generated by Django 4.2.1 on 2023-05-23 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_api', '0002_alter_audiofileserializer_audio_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiofileserializer',
            name='name',
            field=models.CharField(default='name', max_length=200),
        ),
    ]
